export default new Map<String, String>([
  ['tf.0.5s', '0.5s'],
  ['tf.1s', '1.0s'],
  ['tf.2s', '2.0s'],
  ['tf.5s', '5.0s'],
  ['tf.10s', '10s'],
  ['tf.30s', '30s'],
  ['tf.variableFast', 'Really fast (0.0s-0.6s, varying)'],
  ['tf.variableMedium', 'Fast (0.2s-1.2s, varying)'],
  ['tf.variableSlow', 'Slow - Recommended for captions! - (3.4-5.4s, varying)'],
  ['tf.variableSlowest', 'Slowest - Recommended for captions! - (varying)'],
  ['tf.assault', '60fps'],
  ['if.any', 'All images'],
  ['if.gifs', 'Only gifs'],
  ['if.stills', 'Only stills'],
  ['zf.none','No zoom'],
  ['zf.in','Zoom In'],
  ['zf.out','Zoom Out'],
]);